name: Daily Quantum Poetry Generation

on:
  schedule:
    - cron: '0 8 * * *'  # Runs at 8 AM UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate_poems:
    runs-on: ubuntu-latest
    timeout-minutes: 88  # Increased to 88 minutes to accommodate all 8 poems (8 poems * 8 minutes + buffer)
    permissions:
      contents: write
    
    # Add concurrency to prevent multiple workflows from running simultaneously
    concurrency:
      group: poem-generation
      cancel-in-progress: false  # Don't cancel in-progress runs
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Configure Git
      run: |
        git config --global user.name "elbarroca"
        git config --global user.email "btcto154k@gmail.com"
        git config --global pull.rebase false
        git config --global pull.ff false
        git config --global merge.ff false
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Debug Environment
      run: |
        echo "Current directory: $(pwd)"
        echo "Repository path: ${{ github.workspace }}"
        echo "Python version: $(python --version)"
        echo "Pip version: $(pip --version)"
        ls -la
        
    - name: Create env file
      run: |
        echo "COHERE_API_KEY=${{ secrets.COHERE_API_KEY }}" > .env
        echo "REPO_PATH=${{ github.workspace }}" >> .env
        echo "Created .env file with contents:"
        cat .env
        
    - name: Run Poem Generation
      run: |
        # Debug info
        echo "Starting poem generation at $(date)"
        echo "Current directory: $(pwd)"
        echo "Repository contents:"
        ls -la
        
        # Ensure we're on main branch and up to date
        git fetch origin main
        git checkout main
        git pull origin main --no-rebase
        
        # Run with debug output
        python -u daily_automation.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        REPO_PATH: ${{ github.workspace }}
        GIT_AUTHOR_NAME: "elbarroca"
        GIT_AUTHOR_EMAIL: "btcto154k@gmail.com"
        GIT_COMMITTER_NAME: "elbarroca"
        GIT_COMMITTER_EMAIL: "btcto154k@gmail.com"
        PYTHONUNBUFFERED: "1"  # Ensure Python output is not buffered