name: Daily Quantum Poetry Generation

on:
  schedule:
    - cron: '0 8 * * *'  # Runs at 8 AM UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate_poems:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # Set a 2-hour timeout
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Configure Git
      run: |
        git config --global user.name "elbarroca"
        git config --global user.email "btcto154k@gmail.com"
        git config --global pull.rebase false
        git config --global pull.ff false
        git config --global merge.ff false
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git fetch origin main
        git checkout main
        git pull origin main --no-rebase
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cohere gitpython python-dotenv
        
    - name: Create env file
      run: |
        echo "COHERE_API_KEY=${{ secrets.COHERE_API_KEY }}" > .env
        echo "REPO_PATH=${{ github.workspace }}" >> .env
        
    - name: Run Poem Generation
      run: |
        python daily_automation.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        REPO_PATH: ${{ github.workspace }}
        GIT_AUTHOR_NAME: "elbarroca"
        GIT_AUTHOR_EMAIL: "btcto154k@gmail.com"
        GIT_COMMITTER_NAME: "elbarroca"
        GIT_COMMITTER_EMAIL: "btcto154k@gmail.com"